name: Henry
wheels:
    0:
        x: -0.43
        y: 0.25
        radius: 0.05
        angle: 30
    1:
        x: 0.43
        y: 0.25
        radius: 0.05
        angle: -30
    2:
        x: 0
        y: -0.5
        radius: 0.05
        angle: 90
camera_mount:
    yaw:
        servo: [0, 0]
        calibration: [1, 0]
    pitch:
        servo: [0, 1]
        calibration: [1, 0]
grabber:
    servos:
        vertical: [0, 7]
        left: [0, 5]
        right: [0, 6]

